#!/bin/bash
# Monitor progress for definitive prompts execution

set -e

PROMPT=""
PHASE=""
HELP=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --prompt=*)
            PROMPT="${1#*=}"
            shift
            ;;
        --phase=*)
            PHASE="${1#*=}"
            shift
            ;;
        -h|--help)
            HELP=true
            shift
            ;;
        *)
            echo "Unknown parameter: $1"
            exit 1
            ;;
    esac
done

if [ "$HELP" = true ]; then
    echo "Usage: $0 --prompt=<1|2|3> [--phase=<current>]"
    echo ""
    echo "Options:"
    echo "  --prompt=N    Monitor prompt N (1=consolidacion, 2=security, 3=testing)"
    echo "  --phase=X     Monitor specific phase (optional)"
    echo "  -h, --help    Show this help"
    exit 0
fi

if [ -z "$PROMPT" ]; then
    echo "Error: --prompt parameter is required"
    exit 1
fi

# Set prompt name based on number
case $PROMPT in
    1)
        PROMPT_NAME="consolidacion"
        ;;
    2)
        PROMPT_NAME="security"
        ;;
    3)
        PROMPT_NAME="testing"
        ;;
    *)
        echo "Error: Invalid prompt number. Use 1, 2, or 3."
        exit 1
        ;;
esac

DATE=$(date +%Y%m%d)
PROGRESS_DIR="docs/progress"
PROGRESS_FILE="${PROGRESS_DIR}/prompt${PROMPT}_${PROMPT_NAME}_${DATE}.md"

echo "🔍 Monitoring progress for Prompt ${PROMPT} (${PROMPT_NAME})"
echo "📁 Progress file: $PROGRESS_FILE"

# Create progress file if it doesn't exist
if [ ! -f "$PROGRESS_FILE" ]; then
    mkdir -p "$PROGRESS_DIR"
    cat > "$PROGRESS_FILE" << EOF
# Prompt ${PROMPT} Progress Report - ${PROMPT_NAME^}
Date: $(date)

## Execution Status
- Start Time: $(date)
- Current Phase: ${PHASE:-"Not specified"}
- Status: In Progress

## Phases Completed
- [ ] Phase 1
- [ ] Phase 2  
- [ ] Phase 3
- [ ] Phase 4
- [ ] Phase 5

## Metrics
### Before
- TBD

### After  
- TBD

## Issues Found
- None yet

## Next Steps
- Continue with current phase

---
*Auto-generated by monitor_progress.sh*
EOF
    echo "✅ Created new progress file"
else
    echo "📄 Progress file exists, monitoring..."
fi

# Show current status
echo ""
echo "📊 Current Status:"
echo "=================="
if [ -f "$PROGRESS_FILE" ]; then
    grep -A 5 "## Execution Status" "$PROGRESS_FILE" || echo "No status section found"
    echo ""
    echo "📋 Phases:"
    grep "\- \[" "$PROGRESS_FILE" | head -6 || echo "No phases found"
fi

# Monitor mode if phase is specified
if [ -n "$PHASE" ]; then
    echo ""
    echo "🔄 Monitoring mode active for phase: $PHASE"
    echo "Press Ctrl+C to exit"
    
    while true; do
        sleep 30
        echo "[$(date)] Monitoring phase: $PHASE"
        # Here you could add logic to check specific metrics or logs
    done
fi